class_name AntProfile
extends Resource
## Data definition of an ant type/role: identity, movement and combat stats,
## the pheromones it emits, the steering (influence) profiles it uses, and
## the behavior rules it runs.
##
## Authored through AntDesignerPanel and persisted via ResourceLibrary
## (KIND_PROFILE) under user://behavior/profiles. The default "Worker" role
## is generated by DefaultLibrarySeeder — there is no code factory anymore
## (create_basic_worker() was removed: it hardcoded res:// paths and a spawn
## condition that used identifiers outside the AntSenses whitelist).

#region Identity
@export var name: String :
	set(value):
		name = value
		id = name.to_snake_case()
## Derived from name; used as the ResourceLibrary id, the on-disk filename,
## and the Ant.role string. Not exported — re-derived by the setter on load.
var id: String

## Coarse category for UI grouping and sensible combat defaults.
@export_enum("worker", "soldier", "scout", "custom")
var role_type: String = "worker"
#endregion


#region Spawning
## Colony spawn gate, evaluated through EvaluationSystem. Null means the role
## is never auto-spawned — it is only placed as one of a colony's initial ants.
@export var spawn_condition: Logic
#endregion


#region Stats
@export_group("Stats")
@export var movement_rate: float = 25.0
@export var vision_range: float = 100.0
@export var size: float = 1.0
@export var max_health: float = 100.0
#endregion


#region Combat
@export_group("Combat")
@export var is_combatant: bool = false
@export var attack_damage: float = 0.0
@export var attack_cooldown: float = 0.8
#endregion


#region Composition
@export_group("")
## Pheromones this role emits (each carries its own emit condition).
@export var pheromones: Array[Pheromone]

## Steering profiles evaluated by InfluenceManager for default movement.
@export var movement_influences: Array[InfluenceProfile]

## Behavior rules evaluated each tick, highest priority first.
## Leave empty to use Ant.DEFAULT_RULE_IDS.
@export var behavior_rules: Array[AntRule] = []
#endregion
