class_name AntProfile
extends Resource
## Data definition of an ant type/role: identity, movement and combat stats,
## and the BehaviorProfile that is its complete decision surface — behaviors,
## priorities, and channels, replacing the separate behavior_rules and
## movement_influences of the pre-E2 model (one selection system instead of
## two that could disagree).
##
## Authored through AntDesignerPanel and persisted via ResourceLibrary
## (KIND_PROFILE) under user://behavior/profiles. The default "Worker" role
## is generated by DefaultLibrarySeeder — there is no code factory anymore
## (create_basic_worker() was removed: it hardcoded res:// paths and a spawn
## condition that used identifiers outside the AntSenses whitelist).

#region Identity
@export var name: String :
	set(value):
		name = value
		id = name.to_snake_case()
## Derived from name; used as the ResourceLibrary id, the on-disk filename,
## and the Ant.role string. Not exported — re-derived by the setter on load.
var id: String

## Coarse category for UI grouping and sensible combat defaults.
@export_enum("worker", "soldier", "scout", "custom")
var role_type: String = "worker"
#endregion


#region Spawning
## Colony spawn gate, evaluated through EvaluationSystem. Null means the role
## is never auto-spawned — it is only placed as one of a colony's initial ants.
@export var spawn_condition: Logic
#endregion


#region Stats
@export_group("Stats")
@export var movement_rate: float = 25.0
@export var vision_range: float = 100.0
@export var size: float = 1.0
@export var max_health: float = 100.0
#endregion


#region Combat
@export_group("Combat")
@export var is_combatant: bool = false
@export var attack_damage: float = 0.0
@export var attack_cooldown: float = 0.8
#endregion


#region Composition
@export_group("")
## DEPRECATED (write-orphaned since E2): emission DECISIONS moved to
## signaling-channel behaviors calling emit_pheromone, and heatmap layer
## registration now reads the full KIND_PHEROMONE catalog
## (Ant.register_to_heatmap) — nothing consumes this list at runtime.
## Kept one batch so existing .tres files load without warnings; removal
## is an explicit E3/E4 decision (the builder_data lesson: no silent
## write-orphaned exports left behind).
@export var pheromones: Array[Pheromone]

## The ant's full decision surface: behaviors, priorities, and channels
## (see BehaviorProfile). Referenced, never embedded — the profile resource
## is saved leaves-first like everything else. Null means the ant idles,
## warned once at profile application (Ant._apply_profile_internal).
@export var behavior_profile: BehaviorProfile
#endregion
