class_name InfluenceProfile
extends Resource
## A named steering state: the set of influences that drive movement while
## this profile is active, plus the conditions that activate and release it.
##
## Cataloged by ResourceLibrary (KIND_INFLUENCE_PROFILE) under
## user://behavior/influence_profiles. Defaults (wander / look for food /
## go home) are generated by DefaultLibrarySeeder.
##
## Selection semantics (implemented by InfluenceManager, evaluated every
## physics tick through EvaluationSystem so per-condition eval policies
## control the real cost):
##  - enter_conditions: profile is eligible when ANY is true; an empty list
##    means always eligible. First eligible profile in the ant's list wins.
##  - exit_conditions: while active, a profile that HAS exit conditions is
##    sticky — it holds until any exit condition fires, then selection
##    re-runs. A profile with NO exit conditions is not sticky and can be
##    displaced any tick by an earlier-listed eligible profile (this is what
##    lets an always-eligible fallback like "wander" yield to real states).

@export var name: String = "":
	set(value):
		name = value
		id = name.to_snake_case()
## Derived from name; ResourceLibrary id and on-disk filename.
## Not exported — re-derived by the setter on load.
var id: String

## Any true = eligible for activation. Empty = always eligible.
@export var enter_conditions: Array[Logic] = [] as Array[Logic]

## Any true = release the active profile and re-select. Empty = not sticky.
@export var exit_conditions: Array[Logic] = [] as Array[Logic]

## The steering vectors summed while this profile is active.
## Typed as Logic for legacy-load compatibility; every element is expected
## to be an Influence, and the save gate enforces it.
@export var influences: Array[Logic] = [] as Array[Logic]
