class_name AntBehavior
extends Resource
## A unit of authored behavior: a trigger condition, the channel it competes
## on, the actions it executes while active, and the weighted influence
## entries it contributes to steering when it wins the movement channel.
## The clean-break successor to BOTH AntRule (condition + action + priority)
## and InfluenceProfile (enter/exit + influence set) — one authored thing
## instead of two selection systems that could disagree.
##
## Cataloged by ResourceLibrary (KIND_BEHAVIOR) under
## user://behavior/behaviors. Defaults generated by DefaultLibrarySeeder.
##
## WHAT IS DELIBERATELY NOT HERE:
##  - priority and enabled: membership data, not identity. They live on
##    ProfileEntry so one behavior can appear in many BehaviorProfiles at
##    different priorities (worker's "return home" at max priority vs a
##    scout's at modest priority, same resource).
##  - weights: they live on InfluenceEntry for the same reuse reason.
##
## TRIGGER / RELEASE (evaluated through EvaluationSystem; eval policies
## control the real per-tick cost):
##  - trigger null = always eligible (fallback behaviors like wander).
##  - release null = not sticky: the behavior holds an exclusive channel
##    only while its trigger stays true.
##  - release set = sticky: once this behavior claims an exclusive channel
##    it HOLDS the claim after the trigger goes false, until release fires —
##    hysteresis at the selection layer (retreat at energy < 30, release at
##    energy > 60). A strictly higher-priority triggered behavior on the
##    same channel preempts and CANCELS the hold. Hysteresis lives HERE,
##    never in the condition graph's eval policy (timer-bearing graphs must
##    not use STICKY/EVENT modes — see GraphLogic docs).
##
## Actions run each tick the behavior is active, in order; the whitelist
## boundary is unchanged (every AntAction method must be in Ant.ACTION_API).
## Influence entries are consumed by InfluenceManager only when this
## behavior wins the MOVEMENT channel; on any other channel they are inert.

#region Properties
## Display name, used to generate ID (mirrors Logic naming convention).
@export var name: String = "":
	set(value):
		name = value
		id = name.to_snake_case()
## Derived from name; ResourceLibrary id and on-disk filename.
## Not exported — re-derived by the setter on load.
var id: String

## Description of the behavior's intent (for UI tooltips).
@export var description: String = ""

## Eligibility condition. Null means "always eligible" (fallbacks).
@export var trigger: Logic

## Optional release condition — see class docs for sticky semantics.
## Null means "not sticky".
@export var release: Logic

## The arbitration lane this behavior competes on. Null is a data failure:
## the behavior never runs and the runtime logs it once at activation.
@export var channel: BehaviorChannel

## Actions executed each tick while active, in order. Every method is
## re-checked against Ant.ACTION_API at execution — the safety boundary
## that makes runtime/UI-authored behavior safe.
@export var actions: Array[AntAction] = []

## Weighted steering contributions while this behavior owns the movement
## channel. Embedded wrappers referencing cataloged influences — see
## InfluenceEntry docs for the embedding/leaves rule.
@export var influence_entries: Array[InfluenceEntry] = []
#endregion


## Sticky behaviors hold exclusive channels past trigger loss — see class docs.
func is_sticky() -> bool:
	return release != null


## The owning channel's id, or "" when unassigned (data failure; the
## runtime decides recovery — this resource stays silent per log-once
## doctrine).
func channel_id() -> String:
	if not channel:
		return ""
	return channel.id
