class_name BehaviorProfile
extends Resource
## A named, prioritized collection of behaviors — the complete decision
## surface of one ant archetype ("worker", "scout", "soldier"). This is
## what an AntProfile will reference (E2) in place of its separate
## behavior_rules and movement_influences fields, and what the profiles
## pane in the Behavior Designer CRUDs (E3).
##
## Cataloged by ResourceLibrary (KIND_BEHAVIOR_PROFILE) under
## user://behavior/behavior_profiles — NOT the "profile" kind, which
## remains AntProfile (stats/role identity). Defaults generated by
## DefaultLibrarySeeder; the seeded worker behavior profile deliberately
## mirrors the worker AntProfile's id.
##
## SELECTION SEMANTICS (implemented by BehaviorManager in E2, evaluated
## every physics tick through EvaluationSystem so per-condition eval
## policies control the real cost): entries are walked in descending
## priority; disabled entries are skipped; channels arbitrate
## independently — every triggered behavior on a CONCURRENT channel runs,
## while each EXCLUSIVE channel is claimed by its first triggered behavior,
## subject to sticky holds and higher-priority preemption (see AntBehavior
## docs). The movement channel's winner feeds InfluenceManager.
##
## This resource is deliberately dumb: no per-tick state, no sorting cache.
## The runtime sorts via [method sorted_entries] when the profile is
## (re)assigned or edited, not per tick.

#region Properties
## Display name, used to generate ID (mirrors Logic naming convention).
@export var name: String = "":
	set(value):
		name = value
		id = name.to_snake_case()
## Derived from name; ResourceLibrary id and on-disk filename.
## Not exported — re-derived by the setter on load.
var id: String

## Description of the profile's intent (for UI tooltips).
@export var description: String = ""

## Membership entries. Authoring order is preserved on disk; priority is
## the authoritative ordering — use [method sorted_entries] to consume.
@export var entries: Array[ProfileEntry] = []
#endregion


## A descending-priority copy of [member entries]. Stable enough for
## authoring-scale sizes; the runtime caches the result per assignment
## rather than calling this per tick.
func sorted_entries() -> Array[ProfileEntry]:
	var ordered: Array[ProfileEntry] = entries.duplicate()
	ordered.sort_custom(func(a: ProfileEntry, b: ProfileEntry) -> bool:
		return a.priority > b.priority
	)
	return ordered
