class_name BehaviorChannel
extends Resource
## An arbitration lane for behaviors. Every AntBehavior belongs to exactly
## one channel; channels arbitrate independently each tick, which is what
## lets a pheromone-emitting behavior run WHILE a movement behavior owns
## steering.
##
## Arbitration modes:
##  - EXCLUSIVE: the highest-priority triggered behavior on this channel
##    claims it for the tick; every other behavior on the channel is
##    suppressed. Sticky holds (AntBehavior.release) apply here — a claimed
##    exclusive channel is held until release fires or a strictly
##    higher-priority behavior preempts (preemption cancels the hold).
##  - CONCURRENT: every triggered behavior on this channel runs. No claims,
##    no holds, no suppression.
##
## Channels are data (cataloged by ResourceLibrary under KIND_CHANNEL,
## user://behavior/channels; defaults generated by DefaultLibrarySeeder)
## with ONE privileged id: [constant MOVEMENT_ID]. The runtime hands the
## movement channel's winning behavior's influence entries to
## InfluenceManager for integration; every other channel only runs actions.
##
## Seeded defaults: movement (exclusive), interaction (exclusive),
## signaling (concurrent), background (concurrent).

## The privileged channel id whose exclusive winner drives steering.
## User-defined channels may use any other id.
const MOVEMENT_ID: String = "movement"

enum Arbitration {
	EXCLUSIVE,
	CONCURRENT,
}

#region Properties
## Display name, used to generate ID (mirrors Logic naming convention).
@export var name: String = "":
	set(value):
		name = value
		id = name.to_snake_case()
## Derived from name; ResourceLibrary id and on-disk filename.
## Not exported — re-derived by the setter on load.
var id: String

## How simultaneous triggered behaviors on this channel are resolved.
@export var arbitration: Arbitration = Arbitration.EXCLUSIVE

## Description of the channel's intent (for UI tooltips).
@export var description: String = ""
#endregion


func is_exclusive() -> bool:
	return arbitration == Arbitration.EXCLUSIVE
